//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Vestris Inc.")]
[assembly: System.Reflection.AssemblyProduct("VMWareTasks")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2008-2017 Daniel Doubrovkine, Vestris Inc.")]
[assembly: System.Reflection.AssemblyTrademark("All Rights Reserved")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyVersion("1.9.211.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.9.211.0")]


